"""
basin_config.py  -  Read per-basin TOML config and expose the interface
that etg_baseline_fill.py, diagnostics.py, and etunit_summary.py expect.

This is the only configuration module in the project.  Every basin must
have a config.toml under basins/<basin_key>/, typically generated by
prep_basin.py or prep_custom_basin.py.

Simplified workflow note
------------------------
The baseline is a spatially weighted per-BpS-class mean ETg.  There is no
machine-learning residual model and no terrain covariates, so this config
reader only knows about the ETg raster, the BpS raster, the treatment
shapefile, an optional basin boundary, and a handful of treatment /
adjustment / baseline parameters.

Usage in downstream scripts:

    import basin_config as cfg

    cfg.load_basin("101_SierraValley")
    # or
    cfg.load_basin_from_toml(Path("basins/101_SierraValley/config.toml"))

    # Now use cfg.ETG_TIF, cfg.OUT_DIR, cfg.BUFFER_M, etc.
"""

import re
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib  # Python < 3.11
    except ImportError:
        sys.exit("Python 3.11+ or 'tomli' package required for TOML support.\n"
                 "Install with:  pip install tomli")

_here = Path(__file__).resolve().parent
PROJECT_DIR = _here
BASINS_DIR = PROJECT_DIR / "basins"

# -- Module-level attributes (populated by load_basin) ----------------------
# These are the names that downstream fill/diagnostics/summary scripts
# reference as cfg.ETG_TIF, cfg.OUT_DIR, etc.

STUDY_AREA_NAME = None
DATA_DIR        = None
ETG_TIF         = None
BPS_TIF         = None
TREATMENT_SHP   = None
BOUNDARY_SHP    = None   # optional: basin boundary for the training mask
OUT_DIR         = None
CRS_OVERRIDES   = {}

# Treatment
ATTR_SCALE       = "scale_fctr"
ATTR_REPLACE     = "rplc_rt"
BUFFER_M         = 90.0
FEATHER_WIDTH_PX = 4

# Expert adjustment
BASELINE_ADJUST  = 1.0          # basin-wide scalar (1.0 = no change)
ATTR_ADJUST      = "adj_fctr"   # per-polygon override column in shapefile

# Baseline (spatially weighted per-BpS-class mean)
SPATIAL_WEIGHT_RADIUS_PX = 33   # ~1 km at 30 m; 0 = flat basin-wide class mean
MAX_TRAIN_PIXELS = 500_000
RANDOM_SEED      = 42

# Auto-flagging (flag_irrigated.py: screen polygons for irrigation influence)
FLAG_RATIO_THRESH  = 1.5        # flag if polygon mean ETg >= ratio x its BpS-class baseline
FLAG_MIN_EXCESS_FT = 0.3        # ...and at least this many ft/yr above the baseline
FLAG_BASELINE_PCTL = 50.0       # per-BpS-class baseline percentile over in-basin pixels (50 = median)

# Output
COMPRESS        = "DEFLATE"
PREDICTOR_TIFF  = 2


def load_basin(basin_key: str) -> None:
    """
    Load configuration for a basin by key (e.g. "101_SierraValley").
    Reads  basins/<basin_key>/config.toml.
    """
    toml_path = BASINS_DIR / basin_key / "config.toml"
    if not toml_path.exists():
        sys.exit(
            f"ERROR: config.toml not found for basin '{basin_key}'.\n"
            f"  Expected: {toml_path}\n"
            f"  Run prep_basin.py first, or create config.toml manually."
        )
    load_basin_from_toml(toml_path)


def load_basin_from_toml(toml_path: Path) -> None:
    """
    Load configuration from a specific TOML file.
    Populates module-level attributes so downstream code can use
    ``cfg.ETG_TIF``, ``cfg.OUT_DIR``, etc.
    """
    toml_path = Path(toml_path).resolve()
    basin_dir = toml_path.parent
    input_dir = basin_dir / "input"
    # Raw user-supplied rasters + shapefiles live in source/; the single
    # prep-generated covariate (BpS) lives in input/.  For backward
    # compatibility, if source/ doesn't exist we treat input/ as both.
    source_dir = basin_dir / "source"
    if not source_dir.exists():
        source_dir = input_dir

    # tomllib requires UTF-8 (per the TOML spec).  Config files generated on
    # Windows before the encoding fix may be in cp1252 / latin-1; if the
    # straight read fails we re-encode the file to UTF-8 and retry.
    try:
        with open(toml_path, "rb") as f:
            raw = tomllib.load(f)
    except UnicodeDecodeError:
        text = toml_path.read_text(encoding="cp1252")
        toml_path.write_text(text, encoding="utf-8")
        with open(toml_path, "rb") as f:
            raw = tomllib.load(f)

    g = globals()

    # -- Basin identity ------------------------------------------------------
    basin_section = raw.get("basin", {})
    basin_key = basin_section.get("basin_key", basin_dir.name)
    g["STUDY_AREA_NAME"] = basin_key
    g["DATA_DIR"] = input_dir

    # -- Inputs (prep-generated covariate) + Source (user-supplied) ---------
    # [inputs] fields resolve against input/  (BpS.tif)
    # [source] fields resolve against source/ (etg_tif, treatment_shp,
    #                                          boundary_shp)
    # If [source] is absent, those fields are read from [inputs] instead
    # (legacy) and resolved via source_dir.
    inputs = raw.get("inputs", {})
    source = raw.get("source", inputs)   # legacy: fall back to [inputs]

    # Search order for a referenced file: an absolute path is used as-is;
    # otherwise the name is looked for in source/, then input/, then the basin
    # directory.  This makes the config forgiving about whether user files were
    # dropped in source/ (the convention) or input/, and accepts full paths.
    search_dirs = [d for d in (source_dir, input_dir, basin_dir)
                   if d is not None and d.exists()]

    def _resolve(section, key, base_dir, fallback=None):
        val = section.get(key, fallback)
        if val is None or val == "" or str(val).startswith("#"):
            return None
        p = Path(val)
        if p.is_absolute():
            return p if p.exists() else None
        ordered = [base_dir] + [d for d in search_dirs if d != base_dir]
        for d in ordered:
            cand = d / val
            if cand.exists():
                return cand
        return None

    # Prep-generated covariate (normally input/, but search broadly).
    g["BPS_TIF"] = _resolve(inputs, "bps_tif", input_dir, "BpS.tif")

    # User-supplied source files.
    g["ETG_TIF"]       = _resolve(source, "etg_tif",       source_dir)
    g["TREATMENT_SHP"] = _resolve(source, "treatment_shp", source_dir)

    # Basin boundary shapefile (optional - used for the training mask).
    # If not specified, the fill derives the boundary from the treatment
    # shapefile (or the NWI outline for NWI basins).
    boundary_val = source.get("boundary_shp", "")
    if boundary_val and not str(boundary_val).startswith("#"):
        g["BOUNDARY_SHP"] = _resolve(source, "boundary_shp", source_dir)
        g["BOUNDARY_SHP_CONFIGURED"] = True
        g["BOUNDARY_SHP_MISSING"] = g["BOUNDARY_SHP"] is None
    else:
        g["BOUNDARY_SHP"] = None
        g["BOUNDARY_SHP_CONFIGURED"] = False
        g["BOUNDARY_SHP_MISSING"] = False

    # -- Output directory ----------------------------------------------------
    g["OUT_DIR"] = basin_dir / "output"

    # -- Treatment parameters ------------------------------------------------
    treat = raw.get("treatment", {})
    g["BUFFER_M"]         = float(treat.get("buffer_m", 90.0))
    g["FEATHER_WIDTH_PX"] = int(treat.get("feather_width_px", 4))
    g["ATTR_SCALE"]       = treat.get("attr_scale", "scale_fctr")
    g["ATTR_REPLACE"]     = treat.get("attr_replace", "rplc_rt")

    # -- Expert adjustment parameters ---------------------------------------
    adj = raw.get("adjustment", {})
    g["BASELINE_ADJUST"]  = float(adj.get("baseline_adjust", 1.0))
    g["ATTR_ADJUST"]      = adj.get("attr_adjust", "adj_fctr")

    # -- Baseline parameters -------------------------------------------------
    # Accept both [baseline] (current) and [model] (legacy) section names so
    # older config.toml files keep working.
    baseline = raw.get("baseline", raw.get("model", {}))
    g["SPATIAL_WEIGHT_RADIUS_PX"] = int(
        baseline.get("spatial_weight_radius_px",
                     baseline.get("spatial_fallback_radius_px", 33))
    )
    g["MAX_TRAIN_PIXELS"] = _int_or_none(baseline.get("max_train_pixels", 500_000))
    g["RANDOM_SEED"]      = int(baseline.get("random_seed", 42))

    # -- Auto-flagging parameters (flag_irrigated.py) -----------------------
    flag = raw.get("flag", {})
    g["FLAG_RATIO_THRESH"]  = float(flag.get("ratio_thresh", 1.5))
    g["FLAG_MIN_EXCESS_FT"] = float(flag.get("min_excess_ft", 0.3))
    g["FLAG_BASELINE_PCTL"] = float(flag.get("baseline_pctl", 50.0))

    # -- CRS overrides -------------------------------------------------------
    g["CRS_OVERRIDES"] = raw.get("crs_overrides", {})

    # -- Validate required inputs -------------------------------------------
    missing = []
    for key in ("ETG_TIF", "BPS_TIF", "TREATMENT_SHP"):
        if g[key] is None:
            missing.append(key)
    if missing:
        sys.exit(
            f"ERROR: Missing required inputs for basin '{basin_key}':\n"
            + "\n".join(f"  - {k}: check config.toml and files in "
                        f"{source_dir if k != 'BPS_TIF' else input_dir}"
                        for k in missing)
        )


def available_areas() -> list[str]:
    """Return sorted list of basin keys that have a config.toml.

    Skips the ``_template`` directory (which holds the per-basin config.toml
    template, not a runnable basin).
    """
    if not BASINS_DIR.exists():
        return []
    return sorted(
        d.name for d in BASINS_DIR.iterdir()
        if d.is_dir()
        and not d.name.startswith("_")
        and (d / "config.toml").exists()
    )


# -- Template path + renderer ------------------------------------------------
# The per-basin config.toml is generated from a template at
# basins/_template/config.toml.  Placeholders use Python string.Template
# syntax ($name).  Edit the template to change defaults for NEW basins;
# existing basins' config.toml files are never overwritten.

TEMPLATE_PATH = BASINS_DIR / "_template" / "config.toml"


def render_config_template(substitutions: dict) -> str:
    """Render basins/_template/config.toml with the given substitutions.

    Uses ``string.Template.substitute`` (strict: raises on any unknown or
    missing placeholder) so typos in the template or the caller's dict
    fail loudly.  Returns the rendered TOML as a string.
    """
    from string import Template
    if not TEMPLATE_PATH.exists():
        sys.exit(
            f"ERROR: config template not found at {TEMPLATE_PATH}.\n"
            f"  The prep scripts render new basin config.toml files from "
            f"this template; recreate or restore it to proceed."
        )
    tpl = Template(TEMPLATE_PATH.read_text(encoding="utf-8"))
    return tpl.substitute(substitutions)


# -- Placeholder back-fill ---------------------------------------------------
# A freshly generated config.toml carries "# PLACE ..." placeholders for the
# two user-supplied files, because prep runs before those files are dropped in.
# Re-running prep after they arrive fills the placeholders in, and ONLY the
# placeholders: any value the user has set by hand is left alone.

PLACEHOLDER_PREFIX = "# PLACE"

_SOURCE_FIELD_RE = {
    "etg_tif":       re.compile(r'^(\s*etg_tif\s*=\s*)"([^"]*)"', re.MULTILINE),
    "treatment_shp": re.compile(r'^(\s*treatment_shp\s*=\s*)"([^"]*)"', re.MULTILINE),
}


def is_placeholder(value) -> bool:
    """True if a config value is an unfilled '# PLACE ...' placeholder."""
    return value is None or str(value).strip().startswith(PLACEHOLDER_PREFIX)


def backfill_source_files(config_path: Path, **filenames) -> list[str]:
    """Replace unfilled ``[source]`` placeholders in an existing config.toml.

    Accepts ``etg_tif=`` and/or ``treatment_shp=`` keyword arguments.  A field
    is written only when its current value is still a ``# PLACE ...``
    placeholder and a real filename was detected, so user edits are never
    overwritten.  Comments, formatting, and every other line are preserved.

    Returns the list of field names that were filled in (empty if none).
    """
    config_path = Path(config_path)
    if not config_path.exists():
        return []
    text = config_path.read_text(encoding="utf-8")
    filled = []

    for key, new_value in filenames.items():
        if not new_value or is_placeholder(new_value):
            continue
        pat = _SOURCE_FIELD_RE.get(key)
        if pat is None:
            continue
        m = pat.search(text)
        if m is None or not is_placeholder(m.group(2)):
            continue      # field absent, or already set by the user
        text = text[:m.start()] + f'{m.group(1)}"{new_value}"' + text[m.end():]
        filled.append(key)

    if filled:
        config_path.write_text(text, encoding="utf-8")
    return filled


# -- Helpers -----------------------------------------------------------------

def _int_or_none(val):
    if val is None or val == 0:
        return None
    return int(val)
